# Gemfile

source 'https://rubygems.org'

# Залежності від гемів
gem 'rails', '6.1.4'
gem 'sqlite3', '1.4.2'
gem 'devise', '4.7.1'
gem 'bootstrap', '4.5.2'
gem 'jquery-rails', '4.4.0'
gem 'pundit', '2.1.0'

# Групи гемів (наприклад, розробка, тестування)
group :development, :test do
  gem 'rspec-rails', '5.0.0'
  gem 'byebug', '11.1.3'
end

group :test do
  gem 'capybara', '3.35.3'
end
